[package]
name = "git-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
uuid = { version = "1.15.1", features = ["v4"] }
predicates-core = "1.0.9"

[dev-dependencies]
mockall = "0.13.1"